version: '3.1'

services:
  localactivemq:
    image: webcenter/activemq:5.14.3
    restart: always
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: pw
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613