version: "3.1"
services:
  profile-core-mongodb:
    image: mongo:4.2
    container_name: 'profile-core-mongodb'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - profile-core-db:/data/db
    ports:
      - 37017:27017
  profile-core-redis:
    image: redis:6.2-alpine
    container_name: 'profile-core-redis'
    volumes:
      - profile-core-cache:/data
    ports:
      - '6379:6379'

volumes:
  profile-core-db:
  profile-core-cache: