version: '3.1'

services:

  postgresql:
    image: postgres:12.2
    restart: on-failure
    environment:
      POSTGRES_USER: ad
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: myapp
    ports:
      - 5432:5432
