version: "3.8"
services:
  x_pyroscope:
    image: grafana/pyroscope:latest
    container_name: x_pyroscope
    ports:
      - "4040:4040"   # Pyroscope UI
    extra_hosts:
      - "host.docker.internal:host-gateway"